[build]
  publish = "frontend/build"
  command = "cd frontend && npm ci --legacy-peer-deps && npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  REACT_APP_API_URL = "https://your-backend-api.com"
  REACT_APP_WEBSOCKET_URL = "wss://your-backend-api.com"

[context.deploy-preview.environment]
  REACT_APP_API_URL = "https://your-backend-api.com"
  REACT_APP_WEBSOCKET_URL = "wss://your-backend-api.com"

[context.branch-deploy.environment]
  REACT_APP_API_URL = "http://localhost:5001"
  REACT_APP_WEBSOCKET_URL = "ws://localhost:5001"